version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - java-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: java-servlet
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd123
      MYSQL_ROOT_PASSWORD: pwd123

volumes:
  java-db: