version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: